### ISSUE TITLE
openITCOCKPIT Monitoring Agent 2.0 - Testing

### ISSUE THREAD

**Issue by nook24** [it-novum/openitcockpit-agent#43]
# openITCOCKPIT Monitoring Agent 2.0 - Public Beta

Our community reported different issues with the current openITCOCKPIT Monitoring Agent 1.x. First of all we want to thank you for all your reports. This helps us to find issues and design problems so we can improve the monitoring agent with every new release.

Developing a cross-platform monitoring agent is a challenging task and we learned a lot about developing for Microsoft Windows. Due to most of the reported issues were related to Windows it was our main priority to improve the stability by implementing the Win32 API.

## Happy testing
At the moment version 2.0 is in testing phase. To get best results we kindly ask you to join testing and to report any issues. 

Please report all 2.0 related issues **to this issue**.

## Download
Please see the release notes for more information about what's changed.

Latest nightly release:
- 2.0.3: https://github.com/it-novum/openitcockpit-agent/releases/tag/2.0.3-nightly
- 2.0.2: https://github.com/it-novum/openitcockpit-agent/releases/tag/2.0.2-nightly
- 2.0.1: https://github.com/it-novum/openitcockpit-agent/releases/tag/2.0.1-nightly

![Build Status](https://drone.openitcockpit.io/buildStatus/icon?job=openitcockpit-agent%2F2.0_build)

### Changelog
 - 2.0.3
     - Replace Webserver Code
 - 2.0.2
     - Fix custom checks
- 2.0.1
    - Add build instructions to the readme
    - Add tutorials of how to run the agent with an debugger to the readme
    - Windows
        - New MSI installer (requires PowerShell)
        - Drop .NET dependencies
        - Implement Win32 API into the openITCOCKPIT Monitoring Agent for native service management
        - Rename _oitcAgentSvc_ into _openITCOCKPITAgent_ and set `openITCOCKPIT Monitoring Agent` as display name 
        - Change service start type from _Automatic_ to _Automatic (Delayed start)_
        - Set inbound and outbound rules to Windows Firewall
        - Resolve the issue that multiple firewall rules get created
        - Use installed location from windows Registry
        - Add colored output in PowerhShell
        - Own entry point: `agent_windows.py`
    - Linux
        - Make use of `signal.sigtimedwait` to save some cpu cycles 
        - Own entry point: `agent_nix.py`
    - macOS
        - Move all files to `/Applications/openitcockpit-agent/`
        - Improve `.pkg` Installer to not overwrite configuration files on updates
        - Make use of `signal.sigtimedwait` (if possible) or `time.sleep(5)` to save some cpu cycles 
        - Own entry point: `agent_nix.py`

## News and Updates
This post will be updated frequently.

**Comment by AndiMacTen** [comment]
Hi, thank you very much!
I installed the new agent on a bunch of Windows test servers. Until now it looks good. But what they all have in common is that custom scripts are not executed successfully. In the agent.log I see `2020-11-24 19:45:01,598; ERROR; 67; An error occurred while running custom check "Custom_Check_Status"!`. It's a powershell script.
I'll post a status about the stability of the agent by the end of the week.
cheers.

P.S. First I installed ITC 4.1.3 on the server.
P.P.S. Seeing that there is already a commit related to custom checks, don't know whether this one could fix my issue ;-)

**Comment by nook24** [comment]
Looks like there is an issue with Pythons `subprocess.run()` and PyInstaller. I already started debugging this :)

**Comment by Terminator81** [comment]
have installed it on 2 Windows servers.
on one it looks good so far.

The other server says this in the event log

`Service Control Manager, Das Zeitlimit (30000 ms) wurde beim Warten auf eine Transaktionsrückmeldung von Dienst openITCOCKPITAgent erreicht.`

if you need more information logs etc contact me :)

**Comment by nook24** [comment]
@AndiMacTen 
I build version 2.0.2 which should resolve the custom checks issue. On Windows please make sure to have quotes around your command like in the [README](https://github.com/it-novum/openitcockpit-agent/tree/4ccfff1bbea45fb7c2011745246d6e9c4a354e64#Define-custom-checks).
```
"C:\checks\check_dummy.exe" foo bar
```

@Terminator81 
Could you please provide more information about your system?
- What version of Windows are you using?
- Is this happening while the MSI installer runs?
  - Is the MSI installer reporting any errors or crash?
- Is the agent running?
- Does a manual restart of the service resolve the issue?
- Any infos in `C:\Program Files\it-novum\openitcockpit-agent\agent.log` ?

**Comment by Terminator81** [comment]
Windows Server 2016
Agent is installed without errors
Agent is still running
no manual restart has no effect

`
2020-11-25 07:59:22,118; INFO; 1635; 130.50.100.250 - - [25/Nov/2020 07:59:22] "GET / HTTP/1.1" 200 -
2020-11-25 07:59:45,712; INFO; 457; Running default checks
2020-11-25 08:10:56,815; INFO; 63; Checking auto TLS certificate
2020-11-25 08:10:56,815; INFO; 63; SSL Certificate expires in 275 days on 27-08-2021 (DD-MM-YYYY)
2020-11-25 08:10:56,815; INFO; 63; CA file C:\Program Files\it-novum\openitcockpit-agent\server_ca.crt found and readable
2020-11-25 08:10:56,815; INFO; 63; Agent is running in pull mode
2020-11-25 08:10:56,815; INFO; 63; Starting webserver on 0.0.0.0:3333
2020-11-25 08:10:56,831; INFO; 63; SSL with custom certificate enabled
2020-11-25 08:10:56,831; INFO; 63; Server started at https://0.0.0.0:3333 with a check interval of 30 seconds
2020-11-25 08:10:56,846; DEBUG; 75; Starting new Default Checks Thread 0
2020-11-25 08:10:56,846; DEBUG; 83; Running default checks
2020-11-25 08:11:25,394; ERROR; 67; An error occured during windows services check!
2020-11-25 08:11:25,394; ERROR; 87; Traceback (most recent call last):
  File "psutil\_pswindows.py", line 565, in _wrap_exceptions
  File "psutil\_pswindows.py", line 544, in _query_config
OSError: [WinError 1060] Der angegebene Dienst ist kein installierter Dienst: '(originated from OpenService)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src\checks\default_checks.py", line 541, in run_check
  File "psutil\_pswindows.py", line 633, in as_dict
  File "psutil\_pswindows.py", line 543, in _query_config
  File "contextlib.py", line 135, in __exit__
  File "psutil\_pswindows.py", line 574, in _wrap_exceptions
psutil.NoSuchProcess: psutil.NoSuchProcess service 'CDPUserSvc_457655591' does not exist)

2020-11-25 08:11:25,394; ERROR; 67; An error occured during windows eventlog check!
2020-11-25 08:11:25,394; ERROR; 87; Traceback (most recent call last):
  File "configparser.py", line 789, in get
  File "C:\Users\kress\AppData\Local\Programs\Python\Python39\lib\collections\__init__.py", line 941, in __getitem__
  File "C:\Users\kress\AppData\Local\Programs\Python\Python39\lib\collections\__init__.py", line 933, in __missing__
KeyError: 'wineventlog-logtypes'
`
P.S.
i have restarted the server and installed 2.02 now :) hope it will run better

**Comment by Terminator81** [comment]
after update the agent to 2.0.2 the error is still the same
after a few minutes

**Comment by nook24** [comment]
Looks like the agent tries to get data from an service which is no longer running or maybe crashed? How frequently do you get this message in the event log?

**Comment by Terminator81** [comment]
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src\checks\default_checks.py", line 550, in run_check
  File "configparser.py", line 792, in get
configparser.NoOptionError: No option 'wineventlog-logtypes' in section: 'default'

2020-11-25 16:25:40,540; DEBUG; 75; Starting new Default Checks Thread 0
2020-11-25 16:25:40,540; DEBUG; 83; Running default checks
2020-11-25 16:26:07,306; ERROR; 67; An error occured during windows eventlog check!
2020-11-25 16:26:07,306; ERROR; 87; Traceback (most recent call last):
  File "configparser.py", line 789, in get
  File "C:\Users\kress\AppData\Local\Programs\Python\Python39\lib\collections\__init__.py", line 941, in __getitem__
  File "C:\Users\kress\AppData\Local\Programs\Python\Python39\lib\collections\__init__.py", line 933, in __missing__
KeyError: 'wineventlog-logtypes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src\checks\default_checks.py", line 550, in run_check
  File "configparser.py", line 792, in get
configparser.NoOptionError: No option 'wineventlog-logtypes' in section: 'default'

2020-11-25 16:26:36,729; DEBUG; 75; Starting new Default Checks Thread 0
2020-11-25 16:26:36,729; DEBUG; 83; Running default checks
2020-11-25 17:09:27,770; ERROR; 67; An error occured during windows eventlog check!
2020-11-25 17:09:27,770; ERROR; 87; Traceback (most recent call last):
  File "configparser.py", line 789, in get
  File "C:\Users\kress\AppData\Local\Programs\Python\Python39\lib\collections\__init__.py", line 941, in __getitem__
  File "C:\Users\kress\AppData\Local\Programs\Python\Python39\lib\collections\__init__.py", line 933, in __missing__
KeyError: 'wineventlog-logtypes

During handling of the above exception, another exception occurred:
```

**look like every minute
all servies are running :(**


Question??
User kress is not a user from my domain......who is that?

**Comment by AndiMacTen** [comment]
Installed on the same bunch of servers as yesterday. Haven't run a deinstallation before. 
Custom Checks are working fine now 👍 
Unfortunately one server stopped communicating with ITC after less than an hour `UNKNOWN: cURL error 7: Failed to connect to 1.2.3.4 port 3333: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`
And I had no chance to fix it.

**Comment by Terminator81** [comment]
do you have the same user in the logfile?
looks like it is a user of the programmer?

**Comment by nook24** [comment]
@Terminator81
thanks for the error output, this helped a lot! Looks like in your `config.cnf` is `wineventlog-logtypes` missing. Please add the following to the default section of your config.cnf and restart the agent:
```
# Define comma separated windows event log log types
wineventlog-logtypes = System, Application, Security
```
This should resolve the issue. I also added this as fallback values to the code, so that version 2.0.3 will use a default value if its missing in the config file.

The user `kress` is @lukaskress from our consulting team 🙂 We use one of his Windows Systems to build the `.exe` and MSI installer on. Looks like PyInstaller keeps this in the include path.

@AndiMacTen 
Can you please start the agent in foreground mode on the system which makes problems?
```
C:\Program Files\it-novum\openitcockpit-agent\openitcockpit-agent-python3.exe debug
```
Maybe this will print some useful errors.

**Comment by AndiMacTen** [comment]
Hey @nook24 
on the affected servers stopping the openITCOCKPITAgent Service takes extremely long and ends in 
![image](https://user-images.githubusercontent.com/32490082/100329919-9422a900-2fce-11eb-872b-451eba8ffb97.png)

In the agent output in foreground mode I see messages: 
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "src\checks\default_checks.py", line 497, in run_check
  File "psutil\__init__.py", line 1254, in open_files
  File "psutil\_pswindows.py", line 718, in wrapper
psutil.AccessDenied: psutil.AccessDenied (pid=472, name='wininit.exe')
Traceback (most recent call last):
  File "src\checks\default_checks.py", line 363, in run_check
AttributeError: 'NoneType' object has no attribute 'pid'
Traceback (most recent call last):
  File "src\checks\default_checks.py", line 475, in run_check
AttributeError: 'Process' object has no attribute 'num_fds'
Traceback (most recent call last):
  File "src\checks\default_checks.py", line 475, in run_check
AttributeError: 'Process' object has no attribute 'num_fds'
Traceback (most recent call last):
  File "psutil\_pswindows.py", line 716, in wrapper
  File "psutil\_pswindows.py", line 993, in open_files
PermissionError: [WinError 5] Access is denied
Traceback (most recent call last):
  File "src\checks\default_checks.py", line 497, in run_check
  File "psutil\__init__.py", line 1254, in open_files
  File "psutil\_pswindows.py", line 718, in wrapper
psutil.AccessDenied: psutil.AccessDenied (pid=596, name='services.exe')

Since then the communication between agent and server has stopped and the output prints the following
Traceback (most recent call last):
  File "src\checks\default_checks.py", line 475, in run_check
AttributeError: 'Process' object has no attribute 'num_fds'

This is an output of a Windows Server 2019.

**Comment by Terminator81** [comment]
ok made a clean install now und took the default config.....work for now.....i will report :)

**Comment by AndiMacTen** [comment]
I'm very sorry to report that the number of not responding agents is increasing. 
For me it looks like the agent is not reachable randomly. Here are a few timelines of the OITC_AGENT_ACTIVE check. 
![image](https://user-images.githubusercontent.com/32490082/100346297-e3bf9f80-2fe3-11eb-9df3-2f57a7edccf7.png)
![image](https://user-images.githubusercontent.com/32490082/100346356-ff2aaa80-2fe3-11eb-9a15-345044fd933c.png)

This one self recovered this morning, was working for ~10 minutes before deciding to refuse connections `(UNKNOWN: cURL error 7: Failed to connect to server port 3333: Connection refused)`
![image](https://user-images.githubusercontent.com/32490082/100347661-00f56d80-2fe6-11eb-81fd-91a89b481df0.png)

I can't see anything the servers have in common, except the Windows OS but different versions.

**Comment by Terminator81** [comment]
Same here (about 40min)

![grafik](https://user-images.githubusercontent.com/16563785/100354821-0ad09e00-2ff1-11eb-90ce-669c6205c0de.png)

no Errors in the agent.log

**Comment by nook24** [comment]
Unfortunately this does not happen on my test systems but I figured out that I can crash the agent by holding F5 in Firefox. Fun fact, this only affects Firefox. No issues if I try the same with Chrome or Apache benchmark. So my idea was, that Firefox (or curl in production) does not terminate all connections properly.
I replaced the Agent's Web Server and at least the Firefox issue was gone. Fingers crossed that this will also resolve the connection issues you have.

**Comment by binsky08** [comment]
After starting the agent, the following warning message is still displayed (seen in 2.0.1 and 2.0.3):
`requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!`
System is a Debian 10

**Comment by Terminator81** [comment]
Updated to 2.0.3
lost connection after about 30 min

![grafik](https://user-images.githubusercontent.com/16563785/100588623-6309e780-32f2-11eb-8cf8-ef34133bb863.png)

logfile ....no further entrys after losing connection

**Comment by nook24** [comment]
@Terminator81 
Can you please start the agent in foreground?
```
C:\Program Files\it-novum\openitcockpit-agent\openitcockpit-agent-python3.exe debug
```

**Comment by Terminator81** [comment]
C:\Program Files\it-novum\openitcockpit-agent>openitcockpit-agent-python3.exe debug
requests\__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!
Debugging service openITCOCKPITAgent - press Ctrl+C to stop.
11:48:12 [info] Load agent configuration file "C:\Program Files\it-novum\openitcockpit-agent\config.cnf"
Logfile get saved to C:\Program Files\it-novum\openitcockpit-agent\agent.log
11:48:12 [info] Checking auto TLS certificate
11:48:12 [info] SSL Certificate expires in 361 days on 26-11-2021 (DD-MM-YYYY)
11:48:12 [info] CA file C:\Program Files\it-novum\openitcockpit-agent\server_ca.crt found and readable
11:48:12 [info] Agent version 2.0.3 is running in pull mode
11:48:12 [info] SSL with custom certificate enabled
11:48:12 [info] Server started at https://0.0.0.0:3333 with a check interval of 30 seconds
11:48:12 [info] Load agent custom checks configuration file "C:\Program Files\it-novum\openitcockpit-agent\customchecks.cnf"
11:48:12 [DEBUG] Starting new Default Checks Thread 0
11:48:12 [VERBOSE] Running default checks
11:49:11 [DEBUG] Starting new Default Checks Thread 0
11:49:11 [VERBOSE] Running default checks
11:50:09 [DEBUG] Starting new Default Checks Thread 0
11:50:09 [VERBOSE] Running default checks
11:51:07 [DEBUG] Starting new Default Checks Thread 0
......
12:28:48 [DEBUG] Starting new Default Checks Thread 0
12:28:48 [VERBOSE] Running default checks
12:29:45 [DEBUG] Starting new Default Checks Thread 0
12:29:45 [VERBOSE] Running default checks
12:30:42 [DEBUG] Starting new Default Checks Thread 0
12:30:42 [VERBOSE] Running default checks

its 12:46....as you can see no further entry

**Comment by nook24** [comment]
Have you installed any antivirus on this system and have you already tried to disable it?

**Comment by Terminator81** [comment]
We use Sophos Central. I have defined an exception for the entire folder.

**Comment by Terminator81** [comment]
agents seams to be longer stabel then before
![grafik](https://user-images.githubusercontent.com/16563785/100731850-3924f380-33cc-11eb-82aa-5b1532f22683.png)

**Comment by AndiMacTen** [comment]
Here version 2.0.3 runs stable since installation time. About ~24 hours ago. I'll let you know next week, if there is any change.
Deinstallation of version 2.0.2 was a bit tricky. The service did not stop correctly often and the host did not respond to the reboot command, so I had to reset the host via vcenter...

**Comment by Terminator81** [comment]
i killed the process beforce deinstallation then the deinstallation + installation runs without restart the host.
automation possible :)

**Comment by AndiMacTen** [comment]
Ah good hint, will give it a try.

**Comment by Terminator81** [comment]
better but not stable
![grafik](https://user-images.githubusercontent.com/16563785/100969386-53c5ac80-3533-11eb-9344-424e332e333e.png)

**Comment by nook24** [comment]
Thanks for reporting back. Cant wait to get the results from @AndiMacTen next week.

@binsky08 did you have any connectivity issues on Linux anymore since version 2.0.3?

@Terminator81:
- Do you have this issue an all Windows Systems or just this one?
- Would it be possible for you to run the Python Source code directly?

I will try to implement Pythons `faulthandler` to get more info about whats going wrong on your system.

**Comment by Terminator81** [comment]
@nook24 

- i have installed the new agent on 2 Server, one is running stable the other one is that above :)

- if you tell me how? :)

**Comment by binsky08** [comment]
> Thanks for reporting back. Cant wait to get the results from @AndiMacTen next week.
> 
> @binsky08 did you have any connectivity issues on Linux anymore since version 2.0.3?
> 
> @Terminator81:
> 
>     * Do you have this issue an all Windows Systems or just this one?
> 
>     * Would it be possible for you to run the Python Source code directly?
> 
> 
> I will try to implement Pythons `faulthandler` to get more info about whats going wrong on your system.

Using a cronjob to restart the agent every 6 hours is a good temporary workaround.
However, on my other system with the latest agent version, i have to manually "restart" it every ~48 hours (its different).
"restart" => systemctl openit... restart times out, kills the process, and start it again.

**Comment by AndiMacTen** [comment]
Agent is still running stable. But restarting the service under Windows is almost impossible without killing the process.
Made another interesting discovery. I was wondering about performance data in custom scripts which kept the same value over the last days and digged into it. Without finding a explaination.
Then checked perf data of a built in agent check. In this case check_oitc_agent_cpu_total_percentage. Since agent version 2.0.3 it seems not to be updated after the fist delivery of perf data.
![image](https://user-images.githubusercontent.com/32490082/101175046-f91c7580-3644-11eb-9842-c9a7ff3ee02b.png)
Before 20201203 ~1am agent version < 2.0.3 was running
20201203 ~6.20pm 2.0.3 delivered one perf data value. Since then we have flatten the curve. ;-)
Someone else with the same issue?

P.S. I'm not seeing this behavior on each server updated to agent version 2.0.3.

**Comment by binsky08** [comment]
> Agent is still running stable. But restarting the service under Windows is almost impossible without killing the process.
> Made another interesting discovery. I was wondering about performance data in custom scripts which kept the same value over the last days and digged into it. Without finding a explaination.
> Then checked perf data of a built in agent check. In this case check_oitc_agent_cpu_total_percentage. Since agent version 2.0.3 it seems not to be updated after the fist delivery of perf data.
> ![image](https://user-images.githubusercontent.com/32490082/101175046-f91c7580-3644-11eb-9842-c9a7ff3ee02b.png)
> Before 20201203 ~1am agent version < 2.0.3 was running
> 20201203 ~6.20pm 2.0.3 delivered one perf data value. Since then we have flatten the curve. ;-)
> Someone else with the same issue?

Have not notices that issue ^ yet, but theres a different one.
On one of my systems with the 2.0.3 agent, the CPU graph shows 100% and is steadily increasing.
![grafik](https://user-images.githubusercontent.com/30630233/101178774-b0b38680-3649-11eb-951d-de1881bc5dbe.png)

Manually restarted the agent at **15:22:49** due to check issues (unknown state of OITC_AGENT_ACTIVE) since **14:38:29**.
The points in time exactly match the graph of the total CPU consumption

![grafik](https://user-images.githubusercontent.com/30630233/101179402-71396a00-364a-11eb-8380-a606db05ab70.png)
![grafik](https://user-images.githubusercontent.com/30630233/101179303-5830b900-364a-11eb-9998-1df13a55220f.png)


**Addendum:
I just noticed one of my servers had very high I/O for an hour, 10-15 Mb/s written threw z_vdev_file.
After restarting the agent (thought it was worth a try) the load disappeared after a few seconds.**

**Comment by Terminator81** [comment]
Is a new version in prospect?

**Comment by nook24** [comment]
@AndiMacTen 
> Agent is still running stable. But restarting the service under Windows is almost impossible without killing the process.

Does the system use long running custom checks? Is there a default timeout how long windows will wait until it throw the "can not stop service" error? My wild guess is, that you execute a custom check that runs for lets say 15 seconds, but the windows timeout to stop an process is only 10 seconds or so.

I don't have any issues to stop the agent on my Windows test systems (Windows 10, Server 2016, Server 2019) but I will create a long running script tomorrow and see what happens.

> I was wondering about performance data in custom scripts which kept the same value over the last days and digged into it. Without finding a explaination.
Then checked perf data of a built in agent check. In this case check_oitc_agent_cpu_total_percentage. Since agent version 2.0.3 it seems not to be updated after the fist delivery of perf data.

This is weird. I don't see this neither on Windows, Linux or macOS. All checks and custom checks are reporting their performance data just fine.
I created a custom check on my test bench which will send the current minute as performance data. This looks good so far, I will check tomorrow if it will stuck like in your screenshot.

![Bildschirmfoto 2020-12-08 um 16 10 55](https://user-images.githubusercontent.com/9019992/101501858-8971f780-3970-11eb-8986-8cbc637f1077.png)

@Terminator81 
> Is a new version in prospect?

Yes there will be a new version soon

**Comment by AndiMacTen** [comment]
Hi @nook24 
the custom scripts I run are very simple. Powerhell runtime is less than a second.

I found out it's not just the performance data which is not being updated. It's the whole service output:
![image](https://user-images.githubusercontent.com/32490082/101520541-f1323d80-3984-11eb-9756-9eb79ddbacfe.png)
Configured for pull mode.

**Comment by Terminator81** [comment]
@AndiMacTen
Can you send me a example?

**Comment by AndiMacTen** [comment]
Sure, I've uploaded our widely used script here. Do not expect anything spectacular^^
https://github.com/AndiMacTen/Custom-Monitoring-Plugins/blob/main/check_Windows_Services_Status_OSS.ps1

**Comment by RRonGit** [comment]
Hi,

Bei uns nach wie vor ähnliches Verhalten:

Windows Server 2019 Standart (VM in einer VMware vSphere Umgebung)
Agent Version 2.0.3
Agent ist im Pull Modus (alles standartmässig konfiguriert)
OpenITCockpit Version 4.1.3

Anzeige in OpenITCockpit 09.12.2020, 07.41Uhr:

OK: Agent version 2.0.3 running on Windows (10). Last update: Sat Dec 5 00:31:51 2020

Es steht alles auf grün aber die Daten sind seit dem Sat Dec 5 00:31:51 2020 eingefroren.

Log des Agenten:

2020-12-04 23:38:50,654; DEBUG; 82; Running default checks
2020-12-04 23:38:59,478; INFO; 113; 172.17.0.186 - - [04/Dec/2020 23:38:59] "[37mGET / HTTP/1.1[0m" 200 -
2020-12-04 23:39:37,427; DEBUG; 78; Starting new Custom Checks Thread 0
2020-12-05 00:32:18,473; INFO; 113; 172.17.0.186 - - [05/Dec/2020 00:32:18] "[37mGET / HTTP/1.1[0m" 200 -
2020-12-05 00:32:20,386; DEBUG; 78; Starting new Default Checks Thread 0
2020-12-05 00:33:18,471; INFO; 113; 172.17.0.186 - - [05/Dec/2020 00:33:18] "[37mGET / HTTP/1.1[0m" 200 -
2020-12-05 00:34:18,471; INFO; 113; 172.17.0.186 - - [05/Dec/2020 00:34:18] "[37mGET / HTTP/1.1[0m" 200 -
2020-12-05 00:35:18,473; INFO; 113; 172.17.0.186 - - [05/Dec/2020 00:35:18] "[37mGET / HTTP/1.1[0m" 200 -
2020-12-05 00:36:18,474; INFO; 113; 172.17.0.186 - - [05/Dec/2020 00:36:18] "[37mGET / HTTP/1.1[0m" 200 -
2020-12-05 00:37:18,471; INFO; 113; 172.17.0.186 - - [05/Dec/2020 00:37:18] "[37mGET / HTTP/1.1[0m" 200 -
dann geht es mit der letzten Zeile immer weiter...


Der Fehler trat wieder auf, nachdem ein Snapshot per VeeamBackup & Replication gemacht wurde.

Der Agent verbraucht auch ein bisschen viel RAM:
![image](https://user-images.githubusercontent.com/11077414/101594832-9fc09780-39f2-11eb-833d-3b081a29f616.png)

Der Agent kann per Services nicht neu gestartet werden.
Der Agent muss per Taskmanager beendet werden damit er wieder lauffähig wird.

**Comment by Terminator81** [comment]
@7845258 

Gut das Ich nicht alleine bin 
Welchen virenscanner habt ihr ?

**Comment by RRonGit** [comment]
@Terminator81

Wir haben den von Trendmicro.

**Comment by nook24** [comment]
Thanks @AndiMacTen for providing your script. I added this as an custom check to all my test Windows systems. How ever unfortunately my investigation wasn't relay successfully yet :(

I will come back as soon as I have more information. 

---

@7845258 Danke für deinen Hinweis, schon mal gut das der Webserver noch antwortet, sieht aber nach dem gleichen Problem aus was auch AndiMacTen hat.
Wir arbeiten daran.

**Comment by Terminator81** [comment]
ok dann kann ich auch in deutsch schreiben,
gibt es schon was neues?
aktuell ist der Agent fast nicht einsetzbar. Entweder antwortet er nicht mehr oder frisst immer mehr Speicher

**Comment by nook24** [comment]
Wir arbeiten im Moment an einer Neuentwicklung des Agenten.

**Comment by Terminator81** [comment]
alles klar danke für die Info.

**Comment by Terminator81** [comment]
Gibt es schon eine neue Version die man testen könnte?

**Comment by AndiMacTen** [comment]
A status update would be much appreciated. Thanks.

**Comment by nook24** [comment]
Hi all,
We are working on a complete rewrite of the openITCOCKPIT Agent with _Go_. This will be Version 3.0 and will depend less on external libraries (like psutil with Python) and use more operating system native data sources such as WMI or Perflib on Windows and `/proc` or `/sys` on Linux.

The Go version will also support Windows, Linux and macOS. The basic concept of the Go agent is done and also most of the checks have been implemented already.

Unfortunately it turns out that Python (and the libraries) are unstable when it comes to multi threading and Windows. For this reason we think Python is a dead end so we switch over to a language that can build dependency free native binaries.
While writing this post I can't  say if the Go agent will be compatible with the Python version 1:1. The Python Agent will be EOL as soon as the Go version is released so you should upgrade all your systems anyway.

The Go version requires a new release of openITCOCKPIT. As son as the code base is stable enough I will push the code to a public repository and also release a nightly version of openITCOCKPIT for public testing.

I will update this issue as soon as further information are available.

Regards,

Daniel

**Comment by nook24** [comment]
Hi all,

Thanks for being that patient. As time flies I wanted to give you the next update about the development status of the openITCOCKPIT Monitoring Agent 3.x

The first binaries reached our test bench and we are monitoring for any crashes, memory leaks or other unwanted behaviors.

![agent_3 x_pull_mode](https://user-images.githubusercontent.com/9019992/109182551-59770b00-778d-11eb-8fa5-2c1f716ce32f.png)

Most of the actual development work is completed. Our internal CI system is already building new packages, a lot of documentation has been written and things are looking promising so far.

As soon as the Agent runs stable in the lab, we will launch the public beta to get, with your help, a large variety of different systems.


Regards,

Daniel

**Comment by nook24** [comment]
Today we launched the public beta of the openITCOCKPIT Monitoring Agent 3.0. Please see this blog post for more information:
https://openitcockpit.io/2021/2021/04/14/openitcockpit-monitoring-agent-3-0-public-beta/
